### PR TITLE
use format() instead of SetFormat for RC4

### LINKED ISSUE #28: RC4 via WinAPI?
Anyone know where I can find an RC4 algo using the WinCryptoApi? I'm currently using Laszlo's which looks similar to [the one in this repo](https://github.com/ahkscript/libcrypt.ahk/blob/master/src/RC4.ahk). But both are dependent upon SetFormat which is removed in AHK v2. So I'm hoping for a quick link to an algo using the win api but still encrypts to hex...

### PR DESCRIPTION
**Pull request by mmikeww**
to ensure AHK v2 compatibility

Need @joedf or @hi5 or someone to review the code and make sure it looks good

( and close Issue #28 )

### CODE REVIEW

**Comment by mmikeww** [comment]
the RC4 example still works

**Comment by mmikeww** [comment]
actually AHK v2 would also need to replace `Asc()` with `Ord()` so dunno if this is necessary

**Comment by joedf** [comment]
Seems okay...

**Comment by joedf** [comment]
Works great, thanks! :+1:

**Pull request merged**
